<a href="https://colab.research.google.com/github/mraihanprstya/2048_byme/blob/main/2048_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
class g2048:
  def __init__(self):
    self.matriks = np.zeros((4,4))
    self.genran()
    self.genran()
    self.riw = np.zeros((4,4))
    self.score = 0
  
  def genran(self):
    cek_0 = np.argwhere(self.matriks == 0)
    pick_1 = random.choice(cek_0)
    angka_muncul = np.random.choice([2,4],p=(0.8,0.2))
    self.matriks[pick_1[0],pick_1[1]] = angka_muncul
    # print(self.matriks)
    # return pick_1

  def warp_down(self):
    for j in range(4):
      pos = 3
      for i in range(3):
        if self.matriks[3-i,3-j] == 0 and self.matriks[2-i,3-j] !=0:
          self.matriks[pos,3-j] = self.matriks[2-i,3-j]
          self.matriks[2-i,3-j] = 0
        elif self.matriks[3-i,3-j] == 0 and self.matriks[2-i,3-j] ==0:
          pos += 1
        pos -= 1
    # print(self.matriks)

  def cekger(self):
    temp = (self.matriks != self.riw)
    if True in temp:
      self.genran()

  def tambah(self):
    for j in range(4):
      for i in range(3):
        if self.matriks[3-i,3-j] == self.matriks[2-i,3-j]:
          self.matriks[3-i,3-j] = self.matriks[3-i,3-j]*2
          self.score += self.matriks[3-i,3-j]
          self.matriks[2-i,3-j] = 0
    # print(self.matriks)
    
  def turun(self):
    self.riw = self.matriks*1
    self.warp_down()
    self.tambah()
    self.warp_down()
    self.cekger()
    print(self.matriks)
    print(self.score)
  
  def naik(self):
    self.riw = self.matriks*1
    self.matriks = np.flip(self.matriks,0)
    self.warp_down()
    self.tambah()
    self.warp_down()
    self.matriks = np.flip(self.matriks,0)
    self.cekger()
    print(self.matriks)
    print(self.score)

  def kanan(self):
    self.riw = self.matriks*1
    self.matriks = np.transpose(self.matriks)
    self.warp_down()
    self.tambah()
    self.warp_down()
    self.matriks = np.transpose(self.matriks)
    self.cekger()
    print(self.matriks)
    print(self.score)

  def kiri(self):
    self.riw = self.matriks*1
    self.matriks = np.flip(self.matriks,1)
    self.matriks = np.transpose(self.matriks)
    self.warp_down()
    self.tambah()
    self.warp_down()
    self.matriks = np.transpose(self.matriks)
    self.matriks = np.flip(self.matriks,1)
    self.cekger()
    print(self.matriks)
    print(self.score)
  
  def reset(self):
    self.__init__()
    print(self.matriks)
    
  def undo(self):
    for i in range(4):
      for j in range(4):
        self.matriks[i,j] = self.riw[i,j]
    print(self.matriks)

In [3]:
test = g2048()
print(test.matriks)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [2. 0. 2. 0.]
 [0. 0. 0. 0.]]


In [36]:
test.turun()

[[ 0.  0.  0.  0.]
 [ 4.  4.  0.  0.]
 [ 8.  2.  0.  0.]
 [32.  4.  4.  2.]]
136.0
